---

- name: update nginx statics
  copy:
    src: "files/"
    dest: "/usr/share/nginx/html"
    owner: root
  notify:
    - reload nginx


- firewalld:
      service: https
      permanent: yes
      state: enabled

  notify:
    - restart firewalld


- firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
  notify:
    - restart firewalld

#- name: Bounce firewalld
#  service:
#    name: firewalld
#    state: restarted